services:
  klm_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      driver file:///opt/application/src/main.py
      --airport_data "file:///opt/application/data/airports/airports.dat"
      --bookings_data "file:///opt/application/data/bookings/booking.json"
      --start_date "$START_DATE"
      --end_date "$END_DATE"
      --output "file:///opt/application/out/"
    volumes:
      - ./out:/opt/application/out
      - ./data:/opt/application/data/
    env_file:
      - .env